In [1]:
import pandas as pd 
import numpy as np 
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules

In [2]:
df = pd.read_csv(r"C:\Users\HP\Downloads\Supermarket.csv")
df

    ID                 Products
0    1       Milk, bread, sauce
1    2  Milk, Tea powder, bread
2    3       Bread, Jam, Butter
3    4            Bread, Butter
4    5             Maggie,Sauce
5    6      Maggie,Cheese,Sauce
6    7      Maggie,Cheese,Sauce
7    8     Peanut butter, Bread
8    9      Coffee, Sugar, Milk
9   10              Coffee,Milk
10  11      Maggie,Cheese,Sauce
11  12       Bread, Jam, Butter
12  13            Butter,Cheese
13  14      Maggie,Cheese,Sauce
14  15            Maggie,Bread
15  16         Bread, Torch,Jam
16  17       Bread, Jam, Butter
17  18         Jam,Butter,Torch
18  19       Bread, Jam, Butter
19  20  CornFlakes, Milk, Bread

In [5]:
def split(text):
    return text.split(',')

In [6]:
a = 'jam,butter,maggie'
split(a)

['jam', 'butter', 'maggie']

In [10]:
data = list(df['Products'].apply(split))
data

[['Milk', ' bread', ' sauce'],
 ['Milk', ' Tea powder', ' bread'],
 ['Bread', ' Jam', ' Butter'],
 ['Bread', ' Butter'],
 ['Maggie', 'Sauce'],
 ['Maggie', 'Cheese', 'Sauce'],
 ['Maggie', 'Cheese', 'Sauce'],
 ['Peanut butter', ' Bread'],
 ['Coffee', ' Sugar', ' Milk'],
 ['Coffee', 'Milk'],
 ['Maggie', 'Cheese', 'Sauce'],
 ['Bread', ' Jam', ' Butter'],
 ['Butter', 'Cheese'],
 ['Maggie', 'Cheese', 'Sauce'],
 ['Maggie', 'Bread '],
 ['Bread', ' Torch', 'Jam'],
 ['Bread', ' Jam', ' Butter'],
 ['Jam', 'Butter', 'Torch'],
 ['Bread', ' Jam', ' Butter'],
 ['CornFlakes', ' Milk', ' Bread']]

In [11]:
te = TransactionEncoder()

en_df = te.fit_transform(data)

In [12]:
te.columns_

[' Bread',
 ' Butter',
 ' Jam',
 ' Milk',
 ' Sugar',
 ' Tea powder',
 ' Torch',
 ' bread',
 ' sauce',
 'Bread',
 'Bread ',
 'Butter',
 'Cheese',
 'Coffee',
 'CornFlakes',
 'Jam',
 'Maggie',
 'Milk',
 'Peanut butter',
 'Sauce',
 'Torch']

In [13]:
en_df= pd.DataFrame(en_df, columns=te.columns_)
en_df

     Bread   Butter    Jam   Milk  ...   Milk  Peanut butter  Sauce  Torch
0    False    False  False  False  ...   True          False  False  False
1    False    False  False  False  ...   True          False  False  False
2    False     True   True  False  ...  False          False  False  False
3    False     True  False  False  ...  False          False  False  False
4    False    False  False  False  ...  False          False   True  False
5    False    False  False  False  ...  False          False   True  False
6    False    False  False  False  ...  False          False   True  False
7     True    False  False  False  ...  False           True  False  False
8    False    False  False   True  ...  False          False  False  False
9    False    False  False  False  ...   True          False  False  False
10   False    False  False  False  ...  False          False   True  False
11   False     True   True  False  ...  False          False  False  False
12   False    False  False  False  ...  False          False  False  False
13   False    False  False  False  ...  False          False   True  False
14   False    False  False  False  ...  False          False  False  False
15   False    False  False  False  ...  False          False  False  False
16   False     True   True  False  ...  False          False  False  False
17   False    False  False  False  ...  False          False  False   True
18   False     True   True  False  ...  False          False  False  False
19    True    False  False   True  ...  False          False  False  False

[20 rows x 21 columns]

In [14]:
en_df.replace(False,0,inplace=True)
en_df.replace(True,1,inplace=True)

In [15]:
en_df

     Bread   Butter   Jam   Milk  ...  Milk  Peanut butter  Sauce  Torch
0        0        0     0      0  ...     1              0      0      0
1        0        0     0      0  ...     1              0      0      0
2        0        1     1      0  ...     0              0      0      0
3        0        1     0      0  ...     0              0      0      0
4        0        0     0      0  ...     0              0      1      0
5        0        0     0      0  ...     0              0      1      0
6        0        0     0      0  ...     0              0      1      0
7        1        0     0      0  ...     0              1      0      0
8        0        0     0      1  ...     0              0      0      0
9        0        0     0      0  ...     1              0      0      0
10       0        0     0      0  ...     0              0      1      0
11       0        1     1      0  ...     0              0      0      0
12       0        0     0      0  ...     0              0      0      0
13       0        0     0      0  ...     0              0      1      0
14       0        0     0      0  ...     0              0      0      0
15       0        0     0      0  ...     0              0      0      0
16       0        1     1      0  ...     0              0      0      0
17       0        0     0      0  ...     0              0      0      1
18       0        1     1      0  ...     0              0      0      0
19       1        0     0      1  ...     0              0      0      0

[20 rows x 21 columns]

In [16]:
score = apriori(en_df, min_support=0.2, use_colnames=True)
score

    support                 itemsets
0      0.25                ( Butter)
1      0.20                   ( Jam)
2      0.30                  (Bread)
3      0.25                 (Cheese)
4      0.30                 (Maggie)
5      0.25                  (Sauce)
6      0.20          ( Jam,  Butter)
7      0.25         (Bread,  Butter)
8      0.20            (Bread,  Jam)
9      0.20         (Cheese, Maggie)
10     0.20          (Cheese, Sauce)
11     0.25          (Sauce, Maggie)
12     0.20   (Bread,  Jam,  Butter)
13     0.20  (Cheese, Sauce, Maggie)

In [17]:
model = association_rules(score, metric='lift')
model

         antecedents       consequents  ...  leverage  conviction
0             ( Jam)         ( Butter)  ...    0.1500         inf
1          ( Butter)            ( Jam)  ...    0.1500        4.00
2            (Bread)         ( Butter)  ...    0.1750        4.50
3          ( Butter)           (Bread)  ...    0.1750         inf
4            (Bread)            ( Jam)  ...    0.1400        2.40
5             ( Jam)           (Bread)  ...    0.1400         inf
6           (Cheese)          (Maggie)  ...    0.1250        3.50
7           (Maggie)          (Cheese)  ...    0.1250        2.25
8           (Cheese)           (Sauce)  ...    0.1375        3.75
9            (Sauce)          (Cheese)  ...    0.1375        3.75
10           (Sauce)          (Maggie)  ...    0.1750         inf
11          (Maggie)           (Sauce)  ...    0.1750        4.50
12     (Bread,  Jam)         ( Butter)  ...    0.1500         inf
13  (Bread,  Butter)            ( Jam)  ...    0.1500        4.00
14   ( Jam,  Butter)           (Bread)  ...    0.1400         inf
15           (Bread)   ( Jam,  Butter)  ...    0.1400        2.40
16            ( Jam)  (Bread,  Butter)  ...    0.1500         inf
17         ( Butter)     (Bread,  Jam)  ...    0.1500        4.00
18   (Cheese, Sauce)          (Maggie)  ...    0.1400         inf
19  (Cheese, Maggie)           (Sauce)  ...    0.1500         inf
20   (Sauce, Maggie)          (Cheese)  ...    0.1375        3.75
21          (Cheese)   (Sauce, Maggie)  ...    0.1375        3.75
22           (Sauce)  (Cheese, Maggie)  ...    0.1500        4.00
23          (Maggie)   (Cheese, Sauce)  ...    0.1400        2.40

[24 rows x 9 columns]